name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: m Start
        run: minikube start

      - name: Execute YAML file
        run: |
        kubbectl applay -f deployment.yaml deployment.aps/examle-app-created