name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: m Start
        run: minikube start

      - name: Execute YAML file
        run: |
          curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
          kubectl apply -f deployment.yaml


        
      
      - name: docker login 
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD